name: Purge jsDelivr cache

on:
  push:
    branches:
      - main
    paths:
      - '**/global-s94.js'

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
    
    - name: Purge jsDelivr cache
      id: purge
      run: |
        purge_results=()
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ $file == *"global-s94.js" ]]; then
            echo "Purging cache for $file"
            fullPath="${{ github.repository }}@${{ github.sha }}/$file"
            encodedPath=$(echo $fullPath | sed 's/\//%2F/g')
            purgeUrl="https://purge.jsdelivr.net/gh/$encodedPath"
            response=$(curl -sS -X GET "$purgeUrl")
            echo "Purge request sent for: $fullPath"
            echo "Response: $response"
            if [[ $response == *"\"status\":\"finished\""* ]]; then
              purge_results+=("Purge successful for $file")
            else
              purge_results+=("Purge may have failed for $file")
            fi
          fi
        done
        
        echo "PURGE_RESULTS<<EOF" >> $GITHUB_OUTPUT
        printf '%s\n' "${purge_results[@]}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Check purge results
      run: |
        echo "${{ steps.purge.outputs.PURGE_RESULTS }}"
        if [[ "${{ steps.purge.outputs.PURGE_RESULTS }}" == *"may have failed"* ]]; then
          echo "Some purge operations may have failed. Please check the logs."
          exit 1
        fi