name: Purge jsDelivr cache

on:
  push:
    branches:
      - main
    paths:
      - '**/global-s94.js'

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Purge jsDelivr cache
      run: |
        file="thebosokacompany/global-s94.js"
        echo "Purging cache for $file"
        purgeUrl="https://purge.jsdelivr.net/gh/${{ github.repository }}@main/$file"
        response=$(curl -sS -X GET "$purgeUrl")
        echo "Purge request sent for: $purgeUrl"
        echo "Response: $response"
        
        if [[ $response == *"\"status\":\"finished\""* ]]; then
          echo "Purge completed successfully for $file"
        elif [[ $response == *"\"status\":\"pending\""* ]]; then
          echo "Purge initiated and pending for $file"
        else
          echo "Purge may have failed for $file. Please check manually."
          echo "Full response: $response"
          exit 1
        fi

    - name: Verify file content
      run: |
        sleep 30  # Wait for 30 seconds
        content=$(curl -sS "https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/thebosokacompany/global-s94.js")
        echo "Current file content:"
        echo "$content"
        echo "If the content doesn't look updated, please check manually at https://www.jsdelivr.com/tools/purge"