name: Purge jsDelivr cache and verify

on:
  push:
    branches:
      - main
    paths:
      - '**/global-s94.js'

jobs:
  purge-and-verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get file hash before purge
      run: |
        BEFORE_HASH=$(curl -sS "https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/thebosokacompany/global-s94.js" | md5sum | cut -d' ' -f1)
        echo "BEFORE_HASH=$BEFORE_HASH" >> $GITHUB_ENV

    - name: Purge jsDelivr cache
      run: |
        file="thebosokacompany/global-s94.js"
        echo "Purging cache for $file"
        purgeUrl="https://purge.jsdelivr.net/gh/${{ github.repository }}@main/$file"
        response=$(curl -sS -X GET "$purgeUrl")
        echo "Purge request sent for: $purgeUrl"
        echo "Response: $response"
        
        status=$(echo $response | jq -r '.status')
        
        if [ "$status" = "finished" ] || [ "$status" = "pending" ]; then
          echo "Purge initiated for $file"
        else
          echo "Purge may have failed for $file. Please check manually."
          echo "Full response: $response"
          exit 1
        fi

    - name: Wait and verify
      run: |
        for i in {1..10}; do
          sleep 30
          AFTER_HASH=$(curl -sS "https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/thebosokacompany/global-s94.js" | md5sum | cut -d' ' -f1)
          echo "Attempt $i: Before hash: $BEFORE_HASH, After hash: $AFTER_HASH"
          if [ "$BEFORE_HASH" != "$AFTER_HASH" ]; then
            echo "Content has changed. Purge successful."
            exit 0
          fi
        done
        echo "Content did not change after 5 minutes. Purge may not have propagated yet."
        exit 1

    - name: Final content check
      if: failure()
      run: |
        echo "Final content check:"
        curl -sS "https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/thebosokacompany/global-s94.js"